### ISSUE TITLE
IndexError: list index out of range step1.py main2

### ISSUE THREAD

**Issue by DecayMehls** [d120/beautiful-tucan#12]
tucan-vv search
[]
Traceback (most recent call last):
  File "step1.py", line 587, in <module>
    main()
  File "step1.py", line 68, in main
    main2()
  File "step1.py", line 103, in main2
    course_ids += utils.json_read_or(prefix+"pre-tucan-search.json", lambda: download_tucan_vv_search(current_semester))
  File "/home/User/Workspace/beautiful-tucan/utils.py", line 94, in json_read_or
    data = func()
  File "step1.py", line 103, in <lambda>
    course_ids += utils.json_read_or(prefix+"pre-tucan-search.json", lambda: download_tucan_vv_search(current_semester))
  File "step1.py", line 203, in download_tucan_vv_search
    return get_courses_of_semester(semester_list[0][1])
IndexError: list index out of range

**Comment by drcicero** [comment]
Please use print(semester_list) or import pprint.pprint; pprint(semester_list) or print other variables (print(soup)) for more information.
BTW one potential problem is that your tucan has to be currently in mode german (with your browser) beforehand, else the link called "VV" will not be found (has a different name in english).

**Comment by DecayMehls** [comment]
I'm using Tucan in German regular.
When i'm using english i get a different error.

tucan-vv search
Traceback (most recent call last):
  File "step1.py", line 587, in <module>
    main()
  File "step1.py", line 68, in main
    main2()
  File "step1.py", line 103, in main2
    course_ids += utils.json_read_or(prefix+"pre-tucan-search.json", lambda: download_tucan_vv_search(current_semester))
  File "/home/User/Workspace/beautiful-tucan/utils.py", line 94, in json_read_or
    data = func()
  File "step1.py", line 103, in <lambda>
    course_ids += utils.json_read_or(prefix+"pre-tucan-search.json", lambda: download_tucan_vv_search(current_semester))
  File "step1.py", line 198, in download_tucan_vv_search
    soup = state.tucan_br.getcached(TUCAN_URL + soup.select_one('li[title="Lehrveranstaltungssuche"] a')['href'])
TypeError: 'NoneType' object is not subscriptable

If i understand you correct you want me the but these prints inside the code of step2.py right?

**Comment by DecayMehls** [comment]
Okay it fixed it self.
It seems like i wasnt properly connected to the VPN.
If i'm not connected to the VPN the Current semester is unknown so the semester_list is empty.
